### ISSUE TITLE
Trying to run this without the .exe

### ISSUE THREAD

**Issue by TreeOfSelf** [NickCis/among-us-proxy#5]
Hey, really don't feel like going through building an .exe if I can just simply host and join through the command line.
I am using Windows 10.
I tried running `npm install` in \packages\among-us-proxy\src
I get this error 
`npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/among-us-proxy-dev-utils - Not found
npm ERR! 404
npm ERR! 404  'among-us-proxy-dev-utils@^1.1.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'among-us-proxy'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.`

I was curious if you knew also, I am trying to get Among us to work with more than 10 players. I was able to get a server hosted with the player limit set to 100.  It shows 100 players when you are in the lobby, however, when looking on the local server list it shows 10/10 players when it has 10 players, and clicking it says "Lobby is full, ask host to join next round". I was curious, is this something I could possibly circumvent? I was considering trying to get the proxy to show that the lobby was 1/10 always and perhaps then it would let them join? Or is this something built into the .exe file.

I tried searching the Hex code of the AmongUs.exe as well as the data files and couldn't find the ASCII string for the error message when the lobby is full so I am a little stumped. Thanks.

**Comment by TreeOfSelf** [comment]
I managed to get it running and working by manually `npm install` every missing module, however, it seems there is some built in limitation in the .exe, because all my clients past 10 were getting an error. I wonder if we can get around this somehow?

**Comment by NickCis** [comment]
Hi there!,

You should run the npm install on the root folder repository and also do a bootstrap:

```
npm install
npm run bootstrap
```

Then you can run the command line util from the `packages/among-us-proxy` folder: `node src/main.js`. I must highlight that you'll probably want to use the electro ui as it also spins up an ngrok instance in order to expose the necessary ports (run `npm start` from `packages/gui`).

Regarding the limit, how did you host a server with the player limit increase?. I don't know if the game checks the number that is sent in the discovery message (I would bet that it doesn't, you can try with different hardcoded values changing it from the [broadcasted message](https://github.com/NickCis/among-us-proxy/blob/master/packages/among-us-proxy/src/among-us/Server.js#L35)).

Server's may send a disconnect message to clients (are the `0x09` message codes), this message can contain a description of why they are disconnecting you.

As the proxy sits in the middle of the game and the server, you can modify messages in that layer, e.g.: making believe the client that there are less users connected. But, I won't think that this would really work. Can you give a in depth explanation about what you are trying to achieve?

**Comment by TreeOfSelf** [comment]
I am trying to connect over 10 players, you can easily set the lobby to show a max player limit of over 10, either by editing the memory address or by editing the file `gameHostOptions` under `AppData\LocalLow\Innersloth\Among Us` Its jus a HEX value in there. The problem is, if I run faker.js say, 20 times? The first 9 will connect fine, but then they start displaying this: 
![image](https://user-images.githubusercontent.com/53889485/95284518-9745b800-081b-11eb-90c7-ab392507f0b4.png)

**Comment by NickCis** [comment]
I really don't know what that `01 00 01 04 00 01 01 00 00 00` message means. As far as I understand the sever should have answered with a `01 ... 07` message.

I should research about the topic (also, there are some bugs on the fake.js script that create a bad connection).

If you want to check what a real client is doing, you can use the proxy as a man in the middle by using the `among-us` protocol (under the `packages/among-us-proxy` folder:

```
node src/main.js guest among-us://<server-ip> --debug
```

**Comment by TreeOfSelf** [comment]
Sounds good, I will look into it more. Thanks for your help! It would be huge if we could accomplish this.

**Comment by NickCis** [comment]
Please explain me how can I increase the user limit so I can also perform some tests :).

**Comment by TreeOfSelf** [comment]
https://filebin.net/7o0i22t9oenbk2rq/gameHostOptions?t=iyg7sw8o

Put this file in your `AppData\LocalLow\Innersloth\Among Us`

Now, when you create a local server it will be set to a 100 player limit.
**NOTE** you will NOT be able to create a normal game through the host menu in online play UNTIL you click 1-10 on the player limit option. The game will simply crash. Clicking 1-10 will revert the config back to normal.

**Comment by NickCis** [comment]
Ok, I'll try that, can you explain how are you editing that file?

**Comment by TreeOfSelf** [comment]
https://hexed.it/ I uploaded it into here, then I  went and hosted a game and changed the max player limit, I saw which hexadecimal value changed . 
![image](https://user-images.githubusercontent.com/53889485/95290772-4f2e9180-082b-11eb-9830-81ee3a0a263b.png)
64 in decimal form = 100

**Comment by TreeOfSelf** [comment]
Upon further experiments it would seem some sort of hardcoded check is built into the game's .dll/.exe files and this may be out of the scope of this project. Thanks for listening , feel free to close this.

**Comment by NickCis** [comment]
Ok, I'll close it.

You could try the [impostor project](https://github.com/AeonLucid/Impostor) which aims to build an oss Among us replacement (being compatible with current protocol). Maybe it can achieve what you were trying to do!
